USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION ZOMATO_S3_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = "arn:aws:iam::360260271782:role/snowflake-s3-role"
    STORAGE_ALLOWED_LOCATIONS = ('s3://zom-data-ai-pipeline/');


GRANT USAGE ON INTEGRATION ZOMATO_S3_INT TO ROLE DBT_ROLE;
DESC INTEGRATION ZOMATO_S3_INT;